### PR TITLE
Feature project type archive

### PR DESCRIPTION
**Pull request by varffs**

### CODE REVIEW

**Comment by mixcas** [comment]
@varffs im getting this onload
image

**Comment by varffs** [comment]
If you haven't set a featured image it doesnt work as the text is absolute positioned and has no height

**Comment by varffs** [comment]
There could be a min height 2rem value i suppose

**Comment by varffs** [comment]
but it doesnt work if you dont set a thumb anyway

**Comment by mixcas** [comment]
what thumb? u mean, if the project gallery is empty?

**Comment by mixcas** [comment]
u said Feat Image but i dont even get the field.

**Comment by mixcas** [comment]
im getting this now

**Comment by varffs** [comment]
what i just said

**Comment by mixcas** [comment]
yes :)

**Comment by varffs** [comment]
Happy?

**Comment by mixcas** [comment]
why u putting it up on me?! i didn't write the code that doesn't work. idgi

it works now :)

**Comment by varffs** [comment]
Yh it didnt work if there wasnt the correct data. The question really is do marginals like that matter? That case was 1 line of code [that you could easily have added rather than waiting for me in another timezone to be able to] so worth doing I guess. But without the thumbs it looks shit even fixed, so if the data is added wrong sites will never look good so...

**Comment by mixcas** [comment]
Sorry @varffs. I didn't undestood the problem. I thought the third column was the one getting fucked.

**Pull request merged**
