### PR TITLE
Edit front page

### PR DESCRIPTION
**Pull request by varffs**
- one image not whole gallery
- cover image feature functions like css cover but with

### CODE REVIEW

**Comment by mixcas** [comment]
@varffs on the PR description, "cover image feature functions like css cover but with" ???

**Comment by mixcas** [comment]
Is it an `` element because `src-set`? It could have been so elegant with http://caniuse.com/#search=image-set

Otherwise it could have been just a real background.

**Comment by varffs** [comment]
Damn I knew that was coming but didnt realise webkit supported it already. But on the other hand 60% global coverage is pretty good so could be progressive enhancement, especially considering it is mac devices that have the most high DPI screens and therefore almost certainly use a webkit browser. Next time I think I will go with that image-set css

**Comment by mixcas** [comment]
Yeah, i'ts good to know it has better support know.

**Pull request merged**
